FLASK_APP=main.py
FLASK_DEBUG=1

DB_HOST=localhost
DB_DATABASE=TO_2_hitung_ipk
DB_USERNAME=root
DB_PASSWORD=

JWT_SECRET=INISECRET

MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=cahyo.test200817@gmail.com
MAIL_PASSWORD=cahyo200817